### PR TITLE
Update to 0.17.0

### PR DESCRIPTION
**Pull request by Darkblader24**

### CODE REVIEW

**Comment by AraHaan** [comment]
This ready? Also mind helping me make an pmd/pmx model file loader that uses opengl and also loads all the other formats that blender supports?

**Comment by a771671** [comment]
2.83 ok?

**Comment by Darkblader24** [comment]
Creating in importer from scratch is a huge task and I don't have the time for that unfortunately. But I can help with coding questions if you encounter them.

**Comment by Darkblader24** [comment]
Also yes it's ready, I haven't released it yet. You can use it by downloading the latest development version via the build-in updater in cats.

**Comment by a771671** [comment]
Hello, my software 2.83 install plugin has a problem and I don't know how to use it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hotox"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上11:28
收件人:&nbsp;"michaeldegroot/cats-blender-plugin"<cats-blender-plugin@noreply.github.com&gt;;
抄送:&nbsp;"yuki"<617869307@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [michaeldegroot/cats-blender-plugin] Update to 0.17.0 (#186)





 
Also yes it's ready, I haven't released it yet. You can use it by downloading the latest development version via the build-in updater in cats.

**Comment by Darkblader24** [comment]
Install this: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip

**Comment by a771671** [comment]
Thank you so much! Thank you! Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hotox"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上11:38
收件人:&nbsp;"michaeldegroot/cats-blender-plugin"<cats-blender-plugin@noreply.github.com&gt;;
抄送:&nbsp;"yuki"<617869307@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [michaeldegroot/cats-blender-plugin] Update to 0.17.0 (#186)





 
Install this: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip

**Comment by shuixiaoben** [comment]
Update, always specified the original 1.61 update can not, how to solve?

**Comment by shuixiaoben** [comment]
In the future, will you consider joining the sinicization?

**Pull request merged**
